name = "NonhomotheticCES"
uuid = "19fc8792-2b89-4883-9e85-8362bf055f3f"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]
version = "0.3.2"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"

[extensions]
ForwardDiffExt = "ForwardDiff"

[compat]
ArgCheck = "2"
DocStringExtensions = "0.8, 0.9"
ForwardDiff = "0.10, 1"
LinearAlgebra = "1.10"
LogExpFunctions = "0.2, 0.3"
StaticArrays = "1.3.2"
julia = "1.10"
